# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ramcha's Blog
email: ramcha1994@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal space where I intend to discuss ideas I find interesting.    
baseurl: /Blog
github_username:  ramcha24

# Build settings
markdown: kramdown
gems:
  - jekyll-gist